name: sirikit_media_intents
description: "A plugin to implement iOS SiriKit Media Intents support in your Flutter app."
version: 0.3.3
repository: https://github.com/nickshoe/sirikit_media_intents

environment:
  sdk: ^3.0.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^22.7.4

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SirikitMediaIntentsPlugin
