// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum INMediaItemType {
  unknown,
  song,
  album,
  artist,
  genre,
  playlist,
  podcastShow,
  podcastEpisode,
  podcastPlaylist,
  musicStation,
  audioBook,
  movie,
  tvShow,
  tvShowEpisode,
  musicVideo,
  podcastStation,
  radioStation,
  station,
  music,
  algorithmicRadioStation,
  news,
}

class INMediaSearch {
  INMediaSearch({
    this.mediaIdentifier,
    required this.mediaType,
    this.mediaName,
    this.artistName,
    this.albumName,
    this.genreNames,
    this.moodNames,
  });

  String? mediaIdentifier;

  INMediaItemType mediaType;

  String? mediaName;

  String? artistName;

  String? albumName;

  List<String>? genreNames;

  List<String>? moodNames;

  Object encode() {
    return <Object?>[
      mediaIdentifier,
      mediaType,
      mediaName,
      artistName,
      albumName,
      genreNames,
      moodNames,
    ];
  }

  static INMediaSearch decode(Object result) {
    result as List<Object?>;
    return INMediaSearch(
      mediaIdentifier: result[0] as String?,
      mediaType: result[1]! as INMediaItemType,
      mediaName: result[2] as String?,
      artistName: result[3] as String?,
      albumName: result[4] as String?,
      genreNames: (result[5] as List<Object?>?)?.cast<String>(),
      moodNames: (result[6] as List<Object?>?)?.cast<String>(),
    );
  }
}

class INMediaItem {
  INMediaItem({
    required this.identifier,
    required this.title,
    required this.type,
    required this.artwork,
    required this.artist,
  });

  String identifier;

  String title;

  INMediaItemType type;

  INImage artwork;

  String artist;

  Object encode() {
    return <Object?>[
      identifier,
      title,
      type,
      artwork,
      artist,
    ];
  }

  static INMediaItem decode(Object result) {
    result as List<Object?>;
    return INMediaItem(
      identifier: result[0]! as String,
      title: result[1]! as String,
      type: result[2]! as INMediaItemType,
      artwork: result[3]! as INImage,
      artist: result[4]! as String,
    );
  }
}

class INImage {
  INImage({
    required this.url,
    required this.width,
    required this.height,
    required this.value,
  });

  String url;

  double width;

  double height;

  int value;

  Object encode() {
    return <Object?>[
      url,
      width,
      height,
      value,
    ];
  }

  static INImage decode(Object result) {
    result as List<Object?>;
    return INImage(
      url: result[0]! as String,
      width: result[1]! as double,
      height: result[2]! as double,
      value: result[3]! as int,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is INMediaItemType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is INMediaSearch) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is INMediaItem) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is INImage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : INMediaItemType.values[value];
      case 130: 
        return INMediaSearch.decode(readValue(buffer)!);
      case 131: 
        return INMediaItem.decode(readValue(buffer)!);
      case 132: 
        return INImage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class IOSSirikitMediaIntentsFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  List<INMediaItem> resolveMediaItems(INMediaSearch mediaSearch);

  void playMediaItems(List<INMediaItem> mediaItems);

  static void setUp(IOSSirikitMediaIntentsFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sirikit_media_intents.IOSSirikitMediaIntentsFlutterApi.resolveMediaItems$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.sirikit_media_intents.IOSSirikitMediaIntentsFlutterApi.resolveMediaItems was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final INMediaSearch? arg_mediaSearch = (args[0] as INMediaSearch?);
          assert(arg_mediaSearch != null,
              'Argument for dev.flutter.pigeon.sirikit_media_intents.IOSSirikitMediaIntentsFlutterApi.resolveMediaItems was null, expected non-null INMediaSearch.');
          try {
            final List<INMediaItem> output = api.resolveMediaItems(arg_mediaSearch!);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sirikit_media_intents.IOSSirikitMediaIntentsFlutterApi.playMediaItems$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.sirikit_media_intents.IOSSirikitMediaIntentsFlutterApi.playMediaItems was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<INMediaItem>? arg_mediaItems = (args[0] as List<Object?>?)?.cast<INMediaItem>();
          assert(arg_mediaItems != null,
              'Argument for dev.flutter.pigeon.sirikit_media_intents.IOSSirikitMediaIntentsFlutterApi.playMediaItems was null, expected non-null List<INMediaItem>.');
          try {
            api.playMediaItems(arg_mediaItems!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

class IOSSirikitMediaIntentsApi {
  /// Constructor for [IOSSirikitMediaIntentsApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  IOSSirikitMediaIntentsApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

}
